### ISSUE TITLE
感谢分享 不过我用demo上传文件时 最后文件大小是0kb的tem文件

### ISSUE THREAD

**Issue by mitang1378** [kazaff/webuploaderDemo#2]
感谢分享 不过我用demo上传文件时 最后文件大小是0kb的tem文件

**Comment by mitang1378** [comment]
上传图片正常 上传的压缩包文件 610M出现上面的问题

**Comment by mitang1378** [comment]
问题找到了，是后台没有增加zip格式

**Comment by kazaff** [comment]
能用就行

**Comment by mitang1378** [comment]
好像还是有点问题，如果同时上传两个或两个以上的文件会出错

**Comment by mitang1378** [comment]
找到原因了 因为开启了prepareNextFile 在上一个文件没传完时就把下一个的文件名传递过去，所以出错
